-- Supabase initialization for jw-life-os

create extension if not exists "uuid-ossp";

create table if not exists public.global_telemetry (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    client_id uuid not null,
    category text not null,
    demographic_tag text not null,
    metrics jsonb not null default '{}'::jsonb
);

create index if not exists idx_global_telemetry_category on public.global_telemetry (category);
create index if not exists idx_global_telemetry_demographic on public.global_telemetry (demographic_tag);
create index if not exists idx_global_telemetry_created_at on public.global_telemetry (created_at desc);

create or replace view public.global_stats as
select
    category,
    demographic_tag,
    count(*)::bigint as sample_size,
    avg((metrics ->> 'mood.score')::numeric) filter (where metrics ? 'mood.score') as avg_mood_score,
    avg((metrics ->> 'health.sleep_hours')::numeric) filter (where metrics ? 'health.sleep_hours') as avg_sleep_hours,
    avg((metrics ->> 'steps')::numeric) filter (where metrics ? 'steps') as avg_steps,
    min(created_at) as first_seen_at,
    max(created_at) as last_seen_at
from public.global_telemetry
group by category, demographic_tag;
